version: '3.8'
services:
  postgres-compose:
    image: postgres
    environment:
      - POSTGRES_PASSWORD="1234"
    ports:
      - "5432:5432"
    volumes:
      - "/Users/mario/Workspaces/MESTRADO_MACKENZIE/COLETA/PROJETO/postgres:/var/lib/postgresql/data"