version: '3.8'
services:
  postgres-compose:
    image: postgres
    environment:
      - POSTGRES_PASSWORD="1234"
    ports:
      - "5432:5432"
    volumes:
      - "/Users/mario/Workspaces/MESTRADO_MACKENZIE/COLETA/PROJETO/postgres:/var/lib/postgresql/data"
  minio:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: ./../.env
    restart: always
    
    